-- =============================================================================
-- 77_content_queue_is_manual.sql
--
-- Content cadence control — marks a post as manually written (via the ops
-- platform's "Write a post" form) rather than generated by the cron/AI
-- pipeline. Used by midnight-cron (skip a brand's day if a manual post
-- already occupies it — see _shared/fill.ts's hasAutoPostOnDate) and by
-- send-digest (labels a post "manual" vs "scheduled").
--
-- FILE ONLY — do not apply via CLI (explicit instruction for this task).
-- =============================================================================

alter table public.mkt_content_queue
  add column if not exists is_manual boolean not null default false;
